### PR TITLE
using System.Text.Json and allow non-object jsons

### PR DESCRIPTION
**Pull request by JTeeuwissen**
Tests at my company would like to use arrays (and strings, but most notably arrays) as valid snapshot values. I rewrote some small parts of the logic to allow this, by using system.text.json.
This includes breaking changes:
- system.text.json requires different config options
- some new snapshots might be formatted differently, although they should remain equal.
- the object wrapper has been removed, to allow for arrays to be used straight up. Perhaps I am missing assumptions as to why they should be objects, but I wouldn't miss the wrapper.

### CODE REVIEW

**Comment by theramis** [comment]
Hi @JTeeuwissen, 

Firstly sorry for the super slow reply!

Secondly thank you so much for the contribution! This is amazing!
I've been meaning to convert Snapper to use `System.Text.Json` for a while now but just never got around to it. 

> Perhaps I am missing assumptions as to why they should be objects

The main reason was that during my initial testing when I first made the library. 
Some of the tooling (like text editors) and some libraries didn't treat arrays as valid json. Back then I incorrectly assumed that for an object to be valid json it had to be an object and not an array. Based on some googling now this doesn't seem to be the case so it's definitely something we can revisit and looking into allowing arrays. 

For next steps on this PR. 
There are two main changes which are both significantly big in my opinion. 
1. Allowing arrays which means some existing snapshots will be shown as diff's and will require regenerating. 
2. Switching to `System.Text.Json`, which might have further smaller changes in how snapshots are generated. 

So my instinct is to release a new major version. Initially a pre-release version and then once there is enough feedback or enough time has passed we I can release it as a stable version. 

How does that sound to you?

**Comment by JTeeuwissen** [comment]
Sounds perfect ;)

**Comment by JTeeuwissen** [comment]
Any update? ;)

**Comment by theramis** [comment]
hey, I'm very sorry, this completely dropped from my mind. 
Working on this now!

**Comment by theramis** [comment]
Merging this into the V3 branch so that I can work on it 😄 

Things that need doing
- Updating docs
- Update changelog
- Bundle in other features/fixes from https://github.com/theramis/Snapper/issues

**Comment by theramis** [comment]
Just released 3.0.0-beta! 
It has all your changes in it! 

Still need to go through the docs and update them. 
Also will probably see if there are any other fixes/issues to include as part of the 3.0.0 release. 

Either way will let 3.0.0 stay in beta for a month or so and then make it official if there are no issues. 

@all-contributors please add @JTeeuwissen for code

**Pull request merged**
